# title: Non-authored PRs merged on GitHub
# description: List of all PRs that I merged on GitHub that were not authored by me.
# sortBy: Merged__At
# pruneFields: mergedBy
# filter: {"operator": "==", "field": "mergedBy", "value": "JeanChristopheMorinPerso"}
# flatten: mergedBy.login
query ($endCursor: String) {
  search(
    # Filtering out Anaconda to avoid SSO errors.
    # Filtering out 'rodeofx/python-api' since it's working related. Same for AnacondaRecipes.
    query: "is:pr is:public is:merged author:JeanChristopheMorinPerso -org:AnacondaRecipes -org:Anaconda -repo:rodeofx/python-api"
    type: ISSUE
    first: 100
    after: $endCursor
  ) {
    edges {
      node {
        ... on PullRequest {
          URL: url
          Title: title
          Created__At: createdAt
          Merged__At: mergedAt
          mergedBy {
            login
          }
          #comments {
          #  totalCount
          #}
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
